from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('departments/', views.departments, name='departments'),
    path('employees/', views.employees, name='employees'),
    path('employees/create/', views.employee_create, name='employee_create'),
    path('employees/<int:pk>/edit/', views.employee_edit, name='employee_edit'),
    path('employees/<int:pk>/delete/', views.employee_delete, name='employee_delete'),
    path('tasks/', views.tasks_list, name='tasks'),
    path('tasks/assign/', views.task_assign, name='task_assign'),
    path('tasks/<int:pk>/submit/', views.task_submit, name='task_submit'),
    path('tasks/<int:pk>/review/', views.task_review, name='task_review'),
    path('attendance/', views.attendance_page, name='attendance'),
    path('attendance/reports/', views.attendance_reports, name='attendance_reports'),
    path('leave/apply/', views.leave_apply, name='leave_apply'),
    path('leaves/', views.leaves_list, name='leaves'),
    path('leaves/<int:pk>/update/', views.leave_update, name='leave_update'),
    path('payroll/', views.payroll_list, name='payroll'),
    path('payroll/create/', views.payroll_assign, name='payroll_assign'),
    path('performance/', views.performance, name='performance'),
    path('announcements/', views.announcements, name='announcements'),
    path('audit-logs/', views.audit_logs, name='audit_logs'),
    path('notifications/', views.notifications, name='notifications'),
    path('documents/', views.documents, name='documents'),
    path('holidays/', views.holidays, name='holidays'),
    path('leave-balances/', views.leave_balances, name='leave_balances'),
    path('reports/', views.reports, name='reports'),
    path('change-password/', views.change_password, name='change_password'),
]
